name: verification

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - 'sample/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

jobs:
  verify:
    name: 👌 Verify libraries
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚙️ Setup GIT versioning
        uses: dotnet/nbgv@v0.4.0
        with:
          setAllVars: true

      - name: 🛠️ Building libraries in release mode
        run: dotnet build -c release -p:ContinuousIntegrationBuild=true

      - name: 🧪 Run unit tests
        run: |
          dotnet test ./test/atc.cosmos.eventstore.tests/atc.cosmos.eventstore.tests.csproj -c release --logger GitHubActions
          dotnet test ./test/atc.cosmos.eventstore.cqrs.tests/atc.cosmos.eventstore.cqrs.tests.csproj -c release --logger GitHubActions

      - name: 🗳️ Pack libraries
        run: |
          dotnet pack -c release -o ${GITHUB_WORKSPACE}/packages -p:ContinuousIntegrationBuild=true
          dotnet pack src/atc.cosmos.eventstore/ -c release -o ${GITHUB_WORKSPACE}/packages -p:ContinuousIntegrationBuild=true
          dotnet pack src/atc.cosmos.eventstore.cqrs/ -c release -o ${GITHUB_WORKSPACE}/packages -p:ContinuousIntegrationBuild=true